version: "3.1"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tickets_app_user
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: ticketsdb
    volumes:
      - ./data:/var/lib/postgresql/data

  # redis:
  #   container_name: redis
  #   image: redis
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis:/data

volumes:
  postgres:
    driver: local
  # redis:
  #   driver: local